name:                toyscheme
version:             0.1.0.0
github:              "ijlion/toyscheme"
license:             WTFPL
author:              "ijlion"
maintainer:          "ijlion@pm.me"

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- haskeline
- mtl
- optparse-applicative
- parsec
- text
- transformers
- HTTP
- tasty
- tasty-golden
- hspec

library:
  source-dirs: src

executables:
  toyscheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toyscheme

tests:
  toyscheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toyscheme
